dist: bionic

git:
  depth: false

addons:
  hosts:
    - magento2.docker

services:
  - docker

language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  matrix:
    - TEST_SUITE=static-unit
    - TEST_SUITE=integration
    - TEST_SUITE=functional

install: composer update

before_script:
  - echo "COMPOSER_MAGENTO_USERNAME=${REPO_USERNAME}" >> ./.env && echo "COMPOSER_MAGENTO_PASSWORD=${REPO_PASSWORD}" >> ./.env
  - echo "COMPOSER_GITHUB_TOKEN=${GITHUB_TOKEN}" >> ./.env

script:
  - if [ $TEST_SUITE == "static-unit" ]; then ./tests/travis/static-unit.sh; fi
  - if [ $TEST_SUITE == "integration" ]; then ./vendor/bin/phpunit --configuration ./tests/integration; fi
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional" ]; then ./tests/travis/functional.sh; fi;

